# make_pdf_embed.py
# Reads PDFs in ./books and writes ./pdf_embed.js with base64 data URLs.

import base64, os, sys

BOOKS_DIR = "books"
SQUARE = os.path.join(BOOKS_DIR, "Spiders_Eight_Legs_of_Awesome_8p5x8p5.pdf")
PORTRAIT = os.path.join(BOOKS_DIR, "Spiders_Eight_Legs_of_Awesome_8x10.pdf")
OUT = "pdf_embed.js"

def b64(path):
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode("ascii")

if not (os.path.exists(SQUARE) and os.path.exists(PORTRAIT)):
    sys.exit(f"Missing PDFs in ./books. Expected:\n - {SQUARE}\n - {PORTRAIT}")

sq = b64(SQUARE)
pt = b64(PORTRAIT)

js = f"""// Auto-generated by make_pdf_embed.py
// HUGE strings ahead. Commit this if you want the site self-contained.

window.PDF_EMBED = {{
  square: 'data:application/pdf;base64,{sq}',
  portrait: 'data:application/pdf;base64,{pt}'
}};
"""

with open(OUT, "w", encoding="utf-8") as f:
    f.write(js)

print(f"Wrote {OUT} with embedded PDFs.")
